package cz.burios.uniql.sql.dsl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import cz.burios.uniql.metadata.DBMetaData;
import cz.burios.uniql.metadata.TableMetaData;
import cz.burios.uniql.model.DynamicRecord;

/** End-to-end H2 test for generated columns and dynamic INSERT. */
public class DynamicRecordGeneratedInsertH2Test {
    public static void main(String[] args) throws Exception {
        String url = "jdbc:h2:mem:uniql_dynamic_generated;DB_CLOSE_DELAY=-1";
        try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
            try (Statement s = connection.createStatement()) {
                s.execute("CREATE TABLE qpx_generated (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            }

            DBMetaData db = DBMetaData.load(connection);
            TableMetaData table = db.table("qpx_generated");
            check(table != null, "table metadata must be loaded");
            check(table.column("id").autoIncrement, "identity column must be detected as auto-increment");

            DynamicRecord record = new DynamicRecord(table);
            record.put("id", 999L);
            record.put("name", "Alice");
            record.put("created", null);

            check(DSL.insert(connection, record) == 1, "INSERT must succeed");
            try (Statement s = connection.createStatement();
                 ResultSet rs = s.executeQuery("SELECT id, name, created FROM qpx_generated")) {
                check(rs.next(), "inserted row must exist");
                check(rs.getLong("id") != 999L, "identity value must be generated by database");
                check("Alice".equals(rs.getString("name")), "writable column must be inserted");
                check(rs.getTimestamp("created") != null, "default timestamp must be generated");
            }
            System.out.println("DynamicRecordGeneratedInsertH2Test: OK");
        }
    }

    private static void check(boolean condition, String message) {
        if (!condition) throw new AssertionError(message);
    }
}
